### Database ##
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties.format_sql: true

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://192.168.99.100:5432/datamining
    username: postgres
    password: 123456
  main:
    banner-mode: 'off'

### JWT Token  ##
security.jwt:
  tokenExpirationTime: 15 # Number of minutes
  refreshTokenExpTime: 60 # Minutes
  tokenIssuer: http://datamining.com
  tokenSigningKey: (YmJZmrj<ETLhFBj2>_JnU$Eft5k*&*e>M3^/?M'pD

## PROFILE DEPS ##
---
spring:
   profiles: prod
logging.config: classpath:log4j2.prod.yml

---
spring:
   profiles: dev
logging.config: classpath:log4j2.dev.yml