server:
  context-path: /api
  port: 8081

spring:
  main:
    banner-mode: 'off'

  ### Database ##
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties.format_sql: true

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:5432/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  ## MAILING ###
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_SENDER_USERNAME}
    password: ${MAIL_SENDER_PASSWORD}
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

  messages:
    basename: i18n/messages

  thymeleaf:
    check-template-location: true
    mode: XHTML
    cache: false
    suffix: .html


### Application specific  ###
### JWT Token  ##
security.jwt:
  tokenExpirationTime: 15 # Number of minutes
  refreshTokenExpTime: 60 # Minutes
  tokenIssuer: ${TOKEN_ISSUER}
  tokenSigningKey: ${TOKEN_SIGNING_KEY}

app:
  async:
    corePoolSize: 3
    maxPoolSize: 50
    queueCapacity: 10000

